### ISSUE TITLE
scroll issue

### ISSUE THREAD

**Issue by durgeshkumar1** [georstat/react-native-synced-list#1]
when we put inside of scrollview it's working fine in ios device but in android not scrolling

can you suggest how we can handle this

**Comment by geobako** [comment]
Hello @durgeshkumar1 

This package consists of a horizontal and a vertical flatlist so putting a flatlist inside a scrollview is not a best practice

**Comment by durgeshkumar1** [comment]
but we have require to put it in the scrollview

**Comment by efstathiosntonas** [comment]
@durgeshkumar1 it's an anti-pattern to nest a flatlist inside a scrollview. We won't support this scenario. 

More info here: https://javascript.plainenglish.io/how-to-fix-virtualizedlists-should-never-be-nested-inside-plain-scrollviews-warning-3a2a887b4ea0
